### ISSUE TITLE
UsersController#update 内の処理をリファクタリングする

### ISSUE THREAD

**Issue by Yama-Souichirou** [tasukuwatanabe/doit#252]
## 概要

対象ファイル: `backend/app/controllers/api/v1/users_controller.rb`
対象メソッド: `update`

### 課題
コードを詳細に追えていないがパッと見限り以下の問題がありそう

1. メソッド内の行数が多いことで可読性、保守性が低い
    * メソッド内に20行前後のコードがあり内部で何をしているのかを理解するコストが高そう
2. if 文が多く手続き型になっている
    * 仕様変更、または仕様追加の対応のコストが高くなることが想定できる
3. コントローラに全てのロジックが含まれているためテスタビリティが低い

### やりたいこと
「課題」に記述した内容を解決、または解消して保守性を向上する。
その際、コストに対する効果はあまり考慮せず現状のコードをより読みやすい形にすることを最優先とする。

#### 具体的にどうするか案
現状仕様を把握していない、且つこのロジックのテストがないので現段階でできそうな対応を上げる
* コントローラ内にロジックを記述しない
  * クラスを分離する
* テストを書く

**Comment by Yama-Souichirou** [comment]
## 仕様メモ

* デフォルト画像に戻すにチェックを入れる
  * 登録画像を消してデフォルト画像が登録される
    * デフォルト画像は carrierwave で設定されている画像を読みに行
    * のでデフォルト画像に戻すにはカラムに保存されている投稿画像を消せば良い
* すでに使用されているメールアドレスかのチェック
* メールアドレスを変更した場合
  * メールを確定した/してないチェック用のカラムを更新する
    * unconifirmed_mail
    * confirmation_token
    * confirmation_digest
    * confirmation_send_at
  * メールアドレスを変更した場合確認用のメールを送る
* メールアドレス以外を更新した場合
  * 更新 or バリデーションエラーを返す

**Comment by tasukuwatanabe** [comment]
#270
